on: push
name: New workflow
jobs:
  setup-android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup-android
      uses: msfjarvis/setup-android@1.0
      with:
        entrypoint: ./gradlew
        args: assembleDebug
